export const CAMPAIGN_DATA = [
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
  {
    initials: "ES",
    fullName: "Epic Social Buzz",
    product: "Samsung",
    date: "2 days ago",
    text: "Aliquam massa donec proin sit duis magna eu maecenas. Ultricies id mattis lobortis proin congue proin elementum. Sed ac porttitor metus ante et suspesstn ....",
    channels: [
      "/assets/instagram.svg",
      "/assets/tiktok.svg",
      "/assets/youtube.svg",
      "/assets/twitter.svg",
      "/assets/facebook.svg",
    ],
    budgetOne: 1000,
    budgetTwo: 1200,
  },
];
